# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoreentry",
            name="ip",
        ),
        migrations.AddField(
            model_name="scoreentry",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
